import React from "react";
import { Link } from "react-router-dom";
import "../App.css";
import "../Images/AttwndifyLogo.svg";
export default function Home() {
  return (
    <div className="home">
      {/* ================= HERO SECTION ================= */}
      <section className="hero-section">
        <div className="hero-content">
          <div className="icon-box">
            <img
              src="AttwndifyLogo.svg"
              alt="Attendify Logo"
              style={{ width: "34px" }}
            />
          </div>
          <h1 className="hero-title">Attendify</h1>
          <p className="hero-subtitle">Smart Attendance Management System</p>
          <p className="hero-desc">
            Attendify modernizes attendance for universities by using a
            simplified class-code check-in system. Fast, secure, and built to
            support students, teachers, and administrators with real-time
            tracking.
          </p>
          <Link to="/login" className="hero-btn">
            Get Started →
          </Link>
        </div>
      </section>
      {/* ================= FEATURES ================= */}
      <section className="features-section">
        <h2 className="section-title">Why Choose Attendify?</h2>
        <p className="section-subtext">
          A modern solution built to simplify attendance for UTAS students and
          staff.
        </p>
        <div className="features-grid">
          <div className="feature-card">
            <div className="icon-box">
              <span style={{ fontSize: "28px", color: "white" }}>⚡</span>
            </div>
            <h3>Instant Check-In</h3>
            <p>
              Students enter a unique class code generated by the teacher—fast,
              secure, and error-free check-ins.
            </p>
          </div>
          <div className="feature-card">
            <div className="icon-box">
              <span style={{ fontSize: "28px", color: "white" }}>📊</span>
            </div>
            <h3>Smart Insights</h3>
            <p>
              Track overall attendance, present/absent percentages, and daily
              performance through clean dashboards.
            </p>
          </div>
          <div className="feature-card">
            <div className="icon-box">
              <span style={{ fontSize: "28px", color: "white" }}>🔒</span>
            </div>
            <h3>Secure System</h3>
            <p>
              Each student, teacher, and admin has a unique role—ensuring your
              attendance data is always protected.
            </p>
          </div>
        </div>
      </section>
      {/* ================= ABOUT US ================= */}
      <section className="about-section">
        <h2 className="section-title">About Attendify</h2>
        <p className="section-subtext">
          A complete attendance solution built specifically for UTAS.
        </p>
        <div className="about-wrapper">
          <div className="about-card">
            <div className="icon-box">
              <span style={{ fontSize: "28px", color: "white" }}>🎓</span>
            </div>
            <ul>
              <li>Designed for UTAS students & staff</li>
              <li>Lightweight and fast architecture</li>
              <li>Accurate & secure class attendance</li>
            </ul>
          </div>
          <div className="mission-box">
            <h3>Our Mission</h3>
            <p>
              To create an attendance system that is simple, secure, and
              efficient— helping instructors manage sessions effortlessly and
              helping students maintain accurate attendance records.
            </p>
            <div className="mission-users">
              ✔ Students — Quick check-in ✔ Teachers — Create class codes ✔
              Admins — Analytics & control
            </div>
          </div>
        </div>
      </section>
      {/* ================= CTA SECTION ================= */}
      <section className="cta-section">
        <h2>Ready to Begin?</h2>
        <p>
          Join hundreds of UTAS students and teachers using Attendify daily.
        </p>
        <Link className="cta-btn" to="/login">
          Start Now →
        </Link>
      </section>
      <footer />
    </div>
  );
}
